import { readFile } from 'node:fs/promises';

/**
 * 从 JSON 文件中提取所有 key
 */
async function extractKeys(filePath: string): Promise<string[]> {
  try {
    const content = await readFile(filePath, 'utf-8');
    const json = JSON.parse(content);
    return Object.keys(json);
  } catch {
    return [];
  }
}

/**
 * 从所有文件中收集所有 key
 */
export async function collectAllKeys(
  files: Record<string, Record<string, string>>
): Promise<Set<string>> {
  const allKeys = new Set<string>();

  // 使用第一个 locale 作为参考
  const firstLocale = Object.keys(files)[0];
  if (!firstLocale) return allKeys;

  for (const filePath of Object.values(files[firstLocale])) {
    const keys = await extractKeys(filePath);
    keys.forEach((key) => allKeys.add(key));
  }

  return allKeys;
}

/**
 * 生成类型定义文件内容
 */
export function generateTypeDefinition(
  keys: Set<string>,
  locales: string[]
): string {
  const keyUnion = Array.from(keys)
    .map((k) => `  | '${k}'`)
    .join('\n');

  const localeUnion = locales.map((l) => `'${l}'`).join(' | ');

  return `// Auto-generated by @shelchin/i18n
// Do not edit manually

declare module '$i18n' {
  export type TranslationKey =
${keyUnion};

  export type Locale = ${localeUnion || 'string'};

  export interface Preferences {
    locale: Locale;
    numberLocale: string;
    currency: string;
    dateLocale: string;
    timezone: string;
  }

  export interface InterpolateParams {
    [key: string]: string | number | bigint;
  }

  /** 翻译函数 */
  export function t(key: TranslationKey, params?: InterpolateParams): string;

  /** 当前 locale */
  export const locale: {
    readonly value: Locale;
    set(value: Locale): void;
  };

  /** 偏好设置 */
  export const preferences: Preferences;

  /** 数字格式化 */
  export function formatNumber(
    value: number | bigint | string,
    options?: {
      style?: 'decimal' | 'currency' | 'percent';
      currency?: string;
      minimumFractionDigits?: number;
      maximumFractionDigits?: number;
      significantDigits?: number;
    }
  ): string;

  /** 货币格式化 */
  export function formatCurrency(
    value: number | bigint | string,
    currency?: string
  ): string;

  /** 日期格式化 */
  export function formatDate(
    date: Date | number | string,
    options?: {
      dateStyle?: 'full' | 'long' | 'medium' | 'short';
      timeStyle?: 'full' | 'long' | 'medium' | 'short';
      timeZone?: string;
    }
  ): string;

  /** 相对时间格式化 */
  export function formatRelativeTime(
    date: Date | number,
    baseDate?: Date | number
  ): string;

  /** 解析本地化数字 */
  export function parseNumber(input: string, locale?: string): string;
}

declare module '$i18n/routes' {
  export const routeMessages: Record<string, string[]>;
}

declare module '$i18n/line-index' {
  export const lineIndex: Record<string, Record<string, { file: string; line: number }>>;
}
`;
}

/**
 * 生成路由映射代码
 */
export function generateRouteMessagesCode(
  routeMessages: Record<string, string[]>
): string {
  // 输出为 .js 文件，不能用 as const
  return `// Auto-generated by @shelchin/i18n
export const routeMessages = ${JSON.stringify(routeMessages, null, 2)};
`;
}
